# Generated by Django 4.2.30 on 2026-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_encryption_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='encrypted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_file_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encryption_iv',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_iv',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
